# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PythonDemonstrateService.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ePythonDemonstrateService.proto\x12\x11PythonDemonstrate\"\xc3\x01\n\x0cStartRequest\x12\r\n\x05modes\x18\x01 \x03(\t\x12\x14\n\x0csamples_path\x18\x02 \x01(\t\x12\x17\n\x0fsave_model_path\x18\x03 \x01(\t\x12\x13\n\x0bvector_size\x18\x04 \x01(\x05\x12\x11\n\titeration\x18\x05 \x01(\x05\x12\x11\n\tmin_count\x18\x06 \x01(\x05\x12\x1f\n\x17save_blocks_visual_path\x18\x07 \x01(\t\x12\x19\n\x11number_of_example\x18\x08 \x01(\x05\"F\n\rStartResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t2h\n\x18PythonDemonstrateService\x12L\n\x05Start\x12\x1f.PythonDemonstrate.StartRequest\x1a .PythonDemonstrate.StartResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PythonDemonstrateService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTREQUEST']._serialized_start=54
  _globals['_STARTREQUEST']._serialized_end=249
  _globals['_STARTRESPONSE']._serialized_start=251
  _globals['_STARTRESPONSE']._serialized_end=321
  _globals['_PYTHONDEMONSTRATESERVICE']._serialized_start=323
  _globals['_PYTHONDEMONSTRATESERVICE']._serialized_end=427
# @@protoc_insertion_point(module_scope)
