# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PythonCorpusService.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19PythonCorpusService.proto\x12\x0cPythonCorpus\"B\n\x0cStartRequest\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x12\n\nremote_url\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\"X\n\rStartResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x10\n\x08progress\x18\x04 \x01(\x02\x32Y\n\x13PythonCorpusService\x12\x42\n\x05Start\x12\x1a.PythonCorpus.StartRequest\x1a\x1b.PythonCorpus.StartResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PythonCorpusService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTREQUEST']._serialized_start=43
  _globals['_STARTREQUEST']._serialized_end=109
  _globals['_STARTRESPONSE']._serialized_start=111
  _globals['_STARTRESPONSE']._serialized_end=199
  _globals['_PYTHONCORPUSSERVICE']._serialized_start=201
  _globals['_PYTHONCORPUSSERVICE']._serialized_end=290
# @@protoc_insertion_point(module_scope)
