# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PythonMLPMetricsAnalysisService.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%PythonMLPMetricsAnalysisService.proto\x12\x18PythonMLPMetricsAnalysis\"^\n\x07Metrics\x12\x0c\n\x04mode\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63\x63uracy\x18\x02 \x01(\x02\x12\x11\n\tprecision\x18\x03 \x01(\x02\x12\x0e\n\x06recall\x18\x04 \x01(\x02\x12\x10\n\x08\x66\x31_score\x18\x05 \x01(\x02\"6\n\x0cStartRequest\x12\r\n\x05modes\x18\x01 \x03(\t\x12\x17\n\x0fsave_model_path\x18\x02 \x01(\t\"{\n\rStartResponse\x12\x31\n\x06result\x18\x01 \x03(\x0b\x32!.PythonMLPMetricsAnalysis.Metrics\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x10\n\x08progress\x18\x04 \x01(\x02\x32}\n\x1fPythonMLPMetricsAnalysisService\x12Z\n\x05Start\x12&.PythonMLPMetricsAnalysis.StartRequest\x1a\'.PythonMLPMetricsAnalysis.StartResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PythonMLPMetricsAnalysisService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRICS']._serialized_start=67
  _globals['_METRICS']._serialized_end=161
  _globals['_STARTREQUEST']._serialized_start=163
  _globals['_STARTREQUEST']._serialized_end=217
  _globals['_STARTRESPONSE']._serialized_start=219
  _globals['_STARTRESPONSE']._serialized_end=342
  _globals['_PYTHONMLPMETRICSANALYSISSERVICE']._serialized_start=344
  _globals['_PYTHONMLPMETRICSANALYSISSERVICE']._serialized_end=469
# @@protoc_insertion_point(module_scope)
