# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PythonMakeWord2VecModelService.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$PythonMakeWord2VecModelService.proto\x12\x17PythonMakeWord2VecModel\"\xa7\x01\n\x0cStartRequest\x12\x1b\n\x13tokenized_data_path\x18\x01 \x01(\t\x12\x12\n\nmodel_path\x18\x02 \x01(\t\x12\x13\n\x0bvector_size\x18\x03 \x03(\x05\x12\x12\n\niterations\x18\x04 \x03(\x05\x12\x11\n\tmin_count\x18\x05 \x03(\x05\x12\x0f\n\x07workers\x18\x06 \x01(\x05\x12\x19\n\x11tokenize_lanquage\x18\x07 \x01(\x05\"F\n\rStartResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t2z\n\x1ePythonMakeWord2VecModelService\x12X\n\x05Start\x12%.PythonMakeWord2VecModel.StartRequest\x1a&.PythonMakeWord2VecModel.StartResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PythonMakeWord2VecModelService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTREQUEST']._serialized_start=66
  _globals['_STARTREQUEST']._serialized_end=233
  _globals['_STARTRESPONSE']._serialized_start=235
  _globals['_STARTRESPONSE']._serialized_end=305
  _globals['_PYTHONMAKEWORD2VECMODELSERVICE']._serialized_start=307
  _globals['_PYTHONMAKEWORD2VECMODELSERVICE']._serialized_end=429
# @@protoc_insertion_point(module_scope)
